interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * World News Feeds MCP.
 *
 * International & world news — foreign-desk and non-English outlets (BBC, Guardian, Le Monde, Der Spiegel, El País, SCMP, Al Jazeera, DW and more).
 * CF-robust RSS / Atom / RDF reader over a curated, edge-verified registry; on a
 * Cloudflare egress block it falls back to the rss2json proxy. (Generated by
 * scripts/gen-feeds-packs.mjs from scripts/feeds-registry.mjs — do not hand-edit.)
 */


const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const PROXY = 'https://api.rss2json.com/v1/api.json';
const MAX_ITEMS = 50;

interface FeedDef { title: string; url: string; category: string; source: string; description: string }

const FEEDS: Record<string, FeedDef> = {
  'bbc-world': { title: "BBC World News", url: "https://feeds.bbci.co.uk/news/world/rss.xml", category: "news", source: "bbc.co.uk", description: "BBC world headlines" },
  'guardian-world': { title: "The Guardian — World", url: "https://www.theguardian.com/world/rss", category: "news", source: "theguardian.com", description: "Guardian world news" },
  aljazeera: { title: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml", category: "news", source: "aljazeera.com", description: "Al Jazeera English — world news" },
  'dw-news': { title: "Deutsche Welle", url: "https://rss.dw.com/rdf/rss-en-all", category: "news", source: "dw.com", description: "Deutsche Welle — German & world news (English)" },
  france24: { title: "France 24", url: "https://www.france24.com/en/rss", category: "news", source: "france24.com", description: "France 24 English — world news" },
  'times-of-india': { title: "Times of India", url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", category: "news", source: "timesofindia.indiatimes.com", description: "India & world top stories" },
  cbc: { title: "CBC News", url: "https://www.cbc.ca/webfeed/rss/rss-topstories", category: "news", source: "cbc.ca", description: "Canadian Broadcasting Corporation top stories" },
  'abc-au': { title: "ABC News (Australia)", url: "https://www.abc.net.au/news/feed/51120/rss.xml", category: "news", source: "abc.net.au", description: "Australian Broadcasting Corporation news" },
  'japan-times': { title: "The Japan Times", url: "https://www.japantimes.co.jp/feed/", category: "news", source: "japantimes.co.jp", description: "Japan & Asia news (English)" },
  'spiegel-intl': { title: "Der Spiegel International", url: "https://www.spiegel.de/international/index.rss", category: "news", source: "spiegel.de", description: "German & world news (English)" },
  scmp: { title: "South China Morning Post", url: "https://www.scmp.com/rss/91/feed", category: "news", source: "scmp.com", description: "Hong Kong, China & Asia news" },
  'the-diplomat': { title: "The Diplomat", url: "https://thediplomat.com/feed/", category: "news", source: "thediplomat.com", description: "Asia-Pacific politics & current affairs" },
  'rest-of-world': { title: "Rest of World", url: "https://restofworld.org/feed/latest/", category: "news", source: "restofworld.org", description: "Tech & culture beyond the West" },
  tagesschau: { title: "Tagesschau", url: "https://www.tagesschau.de/index~rss2.xml", category: "news", source: "tagesschau.de", description: "German news (ARD) — in German" },
  'le-monde': { title: "Le Monde", url: "https://www.lemonde.fr/rss/une.xml", category: "news", source: "lemonde.fr", description: "French news — in French" },
  'el-pais': { title: "El País", url: "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada", category: "news", source: "elpais.com", description: "Spanish news — in Spanish" },
  ansa: { title: "ANSA", url: "https://www.ansa.it/sito/ansait_rss.xml", category: "news", source: "ansa.it", description: "Italian news agency — in Italian" },
  nos: { title: "NOS", url: "https://feeds.nos.nl/nosnieuwsalgemeen", category: "news", source: "nos.nl", description: "Dutch news (NOS) — in Dutch" },
  asahi: { title: "Asahi Shimbun", url: "https://www.asahi.com/rss/asahi/newsheadlines.rdf", category: "news", source: "asahi.com", description: "Japanese news — in Japanese" },
  'inside-higher-ed': { title: "Inside Higher Ed", url: "https://www.insidehighered.com/rss.xml", category: "news", source: "insidehighered.com", description: "US higher-education news" },
  'religion-news': { title: "Religion News Service", url: "https://religionnews.com/feed/", category: "news", source: "religionnews.com", description: "Religion & faith news" },
  'le-figaro': { title: "Le Figaro", url: "https://www.lefigaro.fr/rss/figaro_actualites.xml", category: "news", source: "lefigaro.fr", description: "French news — in French" },
  faz: { title: "FAZ", url: "https://www.faz.net/rss/aktuell/", category: "news", source: "faz.net", description: "German news (FAZ) — in German" },
  'abc-es': { title: "ABC (España)", url: "https://www.abc.es/rss/2.0/portada/", category: "news", source: "abc.es", description: "Spanish news (ABC) — in Spanish" },
  repubblica: { title: "la Repubblica", url: "https://www.repubblica.it/rss/homepage/rss2.0.xml", category: "news", source: "repubblica.it", description: "Italian news — in Italian" },
  folha: { title: "Folha de S.Paulo", url: "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", category: "news", source: "folha.uol.com.br", description: "Brazilian news — in Portuguese" },
  meduza: { title: "Meduza", url: "https://meduza.io/rss/en/all", category: "news", source: "meduza.io", description: "Russia & ex-USSR news (English)" },
  clarin: { title: "Clarín", url: "https://www.clarin.com/rss/lo-ultimo/", category: "news", source: "clarin.com", description: "Argentine news — in Spanish" },
  'jerusalem-post': { title: "The Jerusalem Post", url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", category: "news", source: "jpost.com", description: "Israel & Middle East news (English)" },
  'straits-times': { title: "The Straits Times", url: "https://www.straitstimes.com/news/world/rss.xml", category: "news", source: "straitstimes.com", description: "Singapore & Asia news (English)" },
  'the-hindu': { title: "The Hindu", url: "https://www.thehindu.com/news/national/feeder/default.rss", category: "news", source: "thehindu.com", description: "India national news (English)" },
  'daily-sabah': { title: "Daily Sabah", url: "https://www.dailysabah.com/rssFeed/home", category: "news", source: "dailysabah.com", description: "Turkey & world news (English)" },
  'irish-times': { title: "The Irish Times", url: "https://www.irishtimes.com/cmlink/news-1.1319192", category: "news", source: "irishtimes.com", description: "Ireland & world news" },
  globo: { title: "G1 (Globo)", url: "https://g1.globo.com/rss/g1/", category: "news", source: "g1.globo.com", description: "Brazilian news (G1) — in Portuguese" },
  volkskrant: { title: "de Volkskrant", url: "https://www.volkskrant.nl/voorpagina/rss.xml", category: "news", source: "volkskrant.nl", description: "Dutch news — in Dutch" },
  aftenposten: { title: "Aftenposten", url: "https://www.aftenposten.no/rss", category: "news", source: "aftenposten.no", description: "Norwegian news — in Norwegian" },
  'helsingin-sanomat': { title: "Helsingin Sanomat", url: "https://www.hs.fi/rss/teasers/etusivu.xml", category: "news", source: "hs.fi", description: "Finnish news — in Finnish" },
  politiken: { title: "Politiken", url: "https://politiken.dk/rss/senestenyt.rss", category: "news", source: "politiken.dk", description: "Danish news — in Danish" },
  cna: { title: "Channel NewsAsia", url: "https://www.channelnewsasia.com/rssfeeds/8395986", category: "news", source: "channelnewsasia.com", description: "Channel NewsAsia — Asia news (English)" },
};

const tools: McpToolExport['tools'] = [
  {
    name: 'list_feeds',
    description: 'List the curated international / world-news feeds (id, title, category, source). Optionally filter by category (news) or keyword. Pass an id to read_feed.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Filter by category: news.' },
        query: { type: 'string', description: 'Keyword to match in feed title/source/description.' },
      },
    },
  },
  {
    name: 'read_feed',
    description: 'Read a curated international / world-news feed by its id (from list_feeds). Returns normalized items (title, link, published, summary). Optionally filter items by keyword.',
    inputSchema: {
      type: 'object',
      properties: {
        feed: { type: 'string', description: 'Curated feed id (from list_feeds).' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['feed'],
    },
  },
  {
    name: 'fetch_feed',
    description: 'Fetch and normalize any RSS / Atom / RDF feed by URL. CF-robust: fetches directly and falls back to a proxy if the source blocks the gateway. Use list_feeds first for curated sources.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Feed URL, e.g. "https://news.ycombinator.com/rss".' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['url'],
    },
  },
];

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'list_feeds':
      return listFeeds(args);
    case 'read_feed': {
      const id = String(args.feed ?? '').trim();
      const def = FEEDS[id];
      if (!def) throw new Error(`Unknown feed "${args.feed}". Use list_feeds to see valid ids.`);
      return readFeed(def.url, args, { id, ...def });
    }
    case 'fetch_feed': {
      const url = String(args.url ?? '').trim();
      if (!/^https?:\/\//i.test(url)) throw new Error('Pass a valid feed `url` (http/https).');
      return readFeed(url, args);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function listFeeds(args: Record<string, unknown>): unknown {
  const cat = typeof args.category === 'string' ? args.category.trim().toLowerCase() : '';
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const feeds = Object.entries(FEEDS)
    .filter(([, d]) => (!cat || d.category === cat) && (!q || `${d.title} ${d.source} ${d.description}`.toLowerCase().includes(q)))
    .map(([id, d]) => ({ id, title: d.title, category: d.category, source: d.source, description: d.description }));
  return { categories: [...new Set(Object.values(FEEDS).map((d) => d.category))].sort(), count: feeds.length, feeds };
}

async function readFeed(url: string, args: Record<string, unknown>, meta?: Record<string, unknown>): Promise<unknown> {
  const limit = clamp(numArg(args.limit, 20), 1, MAX_ITEMS);
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const { items, via } = await getFeed(url);
  let out = items;
  if (q) out = out.filter((i) => `${i.title} ${i.summary}`.toLowerCase().includes(q));
  return {
    feed: meta ? { id: meta.id, title: meta.title, source: meta.source } : { url },
    via,
    total_matching: out.length,
    count: Math.min(out.length, limit),
    items: out.slice(0, limit),
  };
}

interface FeedItem { title: string; link: string; published?: string; summary?: string; author?: string; categories?: string[]; id?: string }

async function getFeed(url: string): Promise<{ items: FeedItem[]; via: string }> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml, */*' } });
    if (res.ok) {
      const xml = await res.text();
      if (/<(item|entry)[\s>]/i.test(xml)) return { items: parseFeed(xml), via: 'direct' };
    }
  } catch {
    /* fall through to proxy */
  }
  const pres = await fetch(`${PROXY}?rss_url=${encodeURIComponent(url)}&count=${MAX_ITEMS}`, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  const body = (await pres.json().catch(() => ({}))) as { status?: string; items?: ProxyItem[] };
  if (body.status === 'ok' && Array.isArray(body.items)) {
    return {
      items: body.items.map((i) => ({
        title: clean(i.title), link: i.link || '', published: i.pubDate || undefined,
        summary: clean(i.description)?.slice(0, 500) || undefined, author: i.author || undefined,
        categories: Array.isArray(i.categories) ? i.categories : undefined, id: i.guid || i.link,
      })),
      via: 'proxy',
    };
  }
  throw new Error(`Feed unreachable: ${url} (blocked directly and via proxy). The source may block datacenter egress.`);
}

interface ProxyItem { title?: string; link?: string; pubDate?: string; description?: string; author?: string; categories?: string[]; guid?: string }

function parseFeed(xml: string): FeedItem[] {
  const out: FeedItem[] = [];
  const blocks = xml.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/gi) ?? [];
  for (const b of blocks) {
    const link = extractLink(b);
    out.push({
      title: clean(tag(b, 'title')),
      link,
      published: tag(b, 'pubDate') || tag(b, 'published') || tag(b, 'updated') || tag(b, 'dc:date') || undefined,
      summary: clean(tag(b, 'description') || tag(b, 'summary') || tag(b, 'content:encoded') || tag(b, 'content'))?.slice(0, 500) || undefined,
      author: clean(tag(b, 'dc:creator') || authorName(b)) || undefined,
      categories: cats(b),
      id: tag(b, 'guid') || tag(b, 'id') || link,
    });
  }
  return out;
}

function extractLink(b: string): string {
  const rss = b.match(/<link>([\s\S]*?)<\/link>/i);
  if (rss && rss[1].trim()) return clean(rss[1]);
  const alt = b.match(/<link[^>]*rel=["']alternate["'][^>]*href=["']([^"']+)["']/i) || b.match(/<link[^>]*href=["']([^"']+)["']/i);
  return alt ? alt[1].trim() : '';
}
function authorName(b: string): string {
  const a = b.match(/<author>([\s\S]*?)<\/author>/i);
  if (!a) return '';
  const name = a[1].match(/<name>([\s\S]*?)<\/name>/i);
  return name ? name[1] : a[1];
}
function cats(b: string): string[] | undefined {
  const list: string[] = [];
  for (const m of b.matchAll(/<category[^>]*?(?:term=["']([^"']+)["'][^>]*)?>([\s\S]*?)<\/category>/gi)) {
    const v = clean(m[1] || m[2]);
    if (v) list.push(v);
  }
  for (const m of b.matchAll(/<category[^>]*term=["']([^"']+)["'][^>]*\/>/gi)) list.push(m[1]);
  return list.length ? [...new Set(list)].slice(0, 10) : undefined;
}
function tag(xml: string, name: string): string {
  const m = xml.match(new RegExp(`<${name.replace(':', '\\:')}[^>]*>([\\s\\S]*?)<\\/${name.replace(':', '\\:')}>`, 'i'));
  return m ? unwrap(m[1]) : '';
}
function unwrap(s: string): string {
  const m = s.trim().match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  return (m ? m[1] : s).trim();
}
function clean(s: unknown): string {
  if (typeof s !== 'string') return '';
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/<\/?[a-zA-Z][^>]*>/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ').trim();
}
function numArg(v: unknown, dflt: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN;
  return Number.isFinite(n) ? n : dflt;
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, Math.trunc(n)));
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
